server:
  port: 8082
xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin/
    executor:
      appname: my-job-xxl-job-executor-sample
      logpath: /tmp/
spring:
  active: zhangsan

