server:
  port: 8083
xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin/
    # 必须配置字段
    accessToken: default_token
    executor:
      appname: my-job-01
      logpath: ./tmp/
spring:
  active: zhangsan

logging:
  config: classpath:logback.xml
